image: python:3.8

pipelines:
  default:
    - parallel:
        - step:
            name: Test
            caches:
              - pip
            script:
              # Install dependencies if requirements.txt exists
              - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
              # Install pytest
              - pip install pytest
              # Run the tests (adjust the path to your core app)
              - pytest -v core/tests.py --junitxml=test-reports/report.xml
        - step:
            name: Lint code
            script:
              # Enforce style consistency across Python projects https://flake8.pycqa.org
              - pip install flake8
              # Run flake8 to lint the code (excluding dist, build, and migrations directories)
              - flake8 . --extend-exclude=dist,build,migrations --show-source --statistics
