# Generated by Django 5.1.4 on 2025-01-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthmetrics',
            name='daily_activity_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetrics',
            name='hours_of_sleep',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthmetrics',
            name='resting_heart_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
